const api = {
  baseUrlListing: process.env.REACT_APP_LISTING_URL,
  baseUrl: process.env.REACT_APP_BASE_URL,
  cndUrl: "/s3/images",
  users: "/users",
  login: "/auth/login",
  refreshToken: "/auth/refresh-tokens",
  connectWallets: "api/connect-wallets",
  myNfts: "/users/nfts",
  nfts: "/nft/all",
  nftDetail: "/nfts/detail/",
  nftCreate: "/nfts",
  nftUpdate: "/nfts/",
  nftListing: "/nfts/listing/",
  nftByCollection: "/nft/ByCollection",
  nftFilter: "/nft/filter",
  nftBuy: "/nfts/buy",
  collections: "/collections",
  collection: "/collection/all",
  collectionCategory: "/collection/category/",
  ownerCollection: "/collection/name/",
  myfavorite: "/myfavorite",
  mywatchlist: "/mywatchlist",

  orderTrans: "/order-trans",
  contractabi: "/contractabi",
  usercontract: "/usercontract",
  usercontractNft: "/usercontract/nft",

  nftShowcases: "/nft_showcases.json",
  authors: "/authors.json",
  authorsSales: "/author_ranks.json",
};
export default api;
